export const aminitiesElements = [
  { src: "frame1", text: "24/7 CCTV Surveillance" },
  { src: "frame2", text: "Sauna, Jacuzzi & Massage" },
  { src: "frame3", text: "Dedicated Parking Floor " },
  { src: "frame4", text: "Fully Furnished" },
  { src: "frame5", text: "Servants Residence Office" },
  { src: "frame6", text: "Rooftop Restaurant" },
  { src: "frame7", text: "Infinity Pool" },
  { src: "frame8", text: "Mosque" },
  { src: "frame9", text: "Power Backup" },
  { src: "frame10", text: "Street Lights" },
  { src: "frame11", text: "Refractor Telescope" },
  { src: "frame12", text: "Business & Executive Center" },
  { src: "frame13", text: "Mini Golf Course" },
  { src: "frame14", text: "Air Gun Shooting Range" },
  { src: "frame15", text: "Fitness GYM" },
  { src: "frame16", text: "Rock Climbing" },
  { src: "frame17", text: "Archery" },
  { src: "frame18", text: "Zipline" },
  { src: "frame19", text: "Conference Room" },
  { src: "frame20", text: "Banquet Hall" },
  { src: "frame21", text: "Dedicated Lawn" },
  { src: "frame22", text: "24/7 Frontdesk & Concierge" },
];

export const featuresElements = [
  {
    src: "featureImg1",
    heading: "FOOD AND DRINK",
    text: "Coffee, Tea & Company Roof Top Restaurant",
    width: "24%",
  },
  {
    src: "featureImg2",
    heading: "CLEANING SERVICES",
    text: "Laundry Daily Housekeeping",
    width: "24%",
  },
  {
    src: "featureImg3",
    heading: "ARCHITECTURAL FEATURES",
    text: "Downhill Site Classic Lime Stone Marble Outdoor Finishing Double Glazed UPVC Windows Complete Automation / Smart Home (Optional)",
    width: "47%",
  },
  {
    src: "featureImg4",
    heading: "BUSINESS AND EXECUTIVE CENTER",
    text: "Free WiFi, Photocopy & Printing Email",
    width: "41%",
  },
  {
    src: "featureImg5",
    heading: "Safe And Secure",
    text: "Street Lights, Multiple Fire Escapes, Dedicated Fire Fighting Tanks",
    width: "24%",
  },
  {
    src: "featureImg6",
    heading: "Reception Services",
    text: "24 Hour Front Desk, Express Check In/Check Out, Concierge Service Luggage Storage",
    width: "30%",
  },
  {
    src: "featureImg7",
    heading: "Sports Room",
    text: "Table Tennis, Snooker, Video Games",
    width: "24%",
  },
  {
    src: "featureImg8",
    heading: "Health and Wellness",
    text: "Steam / Sauna, Jacuzzi, Gym, Massage Rooms, Unlimited Natural Spring Water",
    width: "38%",
  },
  {
    src: "featureImg9",
    heading: "Prayer Room",
    text: "",
    width: "33%",
  },
  {
    src: "featureImg10",
    heading: "DEDICATED FLOOR FOR SERVANT ROOMS",
    text: "",
    width: "24%",
  },
  {
    src: "featureImg11",
    heading: "Ease of Access",
    text: "Murree Expressway, Hazara Expressway, Direct Access from Havelian Interchange",
    width: "24%",
  },
  {
    src: "featureImg12",
    heading: "Heating and Power",
    text: "Italian Central Heating System Heated Flooring Generator Backup",
    width: "47%",
  },
];