name: Deployment For test

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Add SSH Key
        id: ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HETZNER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HETZNER_HOST }} >> ~/.ssh/known_hosts

      - name: Build Docker Image
        run: |
          docker build -t serene-heights:latest .

      - name: Copy Docker Image to Server
        env:
          HETZNER_TEST_HOST: ${{ secrets.HETZNER_HOST }}
          HETZNER_USER: ${{ secrets.HETZNER_USER }}
        run: |
          docker save serene-heights:latest | bzip2 | ssh -i ~/.ssh/id_rsa $HETZNER_USER@$HETZNER_TEST_HOST "bunzip2 | docker load"

      - name: Deploy Container on Server
        env:
          HETZNER_TEST_HOST: ${{ secrets.HETZNER_HOST }}
          HETZNER_USER: ${{ secrets.HETZNER_USER }}

        run: |
          ssh -i ~/.ssh/id_rsa $HETZNER_USER@$HETZNER_TEST_HOST << 'EOF'
          docker stop serene-heights || true
          docker rm serene-heights || true
          docker run -d --name serene-heights -p 3000:3000 serene-heights:latest
          EOF
